# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asdq',
            name='author',
        ),
        migrations.RemoveField(
            model_name='asdq',
            name='question',
        ),
        migrations.DeleteModel(
            name='asdq',
        ),
    ]
